FEATURE_COLUMNS = [
    # Сезонные показатели (внутри чемпионата)
    "home_season_points",
    "away_season_points",
    "home_season_goal_diff",
    "away_season_goal_diff",
    "home_season_played",
    "away_season_played",
    "home_season_ppg",
    "away_season_ppg",
    # Атака и оборона (сезон, голы за матч)
    "home_season_gf_pg",
    "away_season_gf_pg",
    "home_season_ga_pg",
    "away_season_ga_pg",
    # Домашние/гостевые сплиты (хозяева дома, гости в гостях)
    "home_home_ppg",
    "away_away_ppg",
    "home_home_gf_pg",
    "home_home_ga_pg",
    "away_away_gf_pg",
    "away_away_ga_pg",
    # Форма (сырая, внутри сезона)
    "home_form_points",
    "away_form_points",
    "home_form_goals_for",
    "away_form_goals_for",
    "home_form_goals_against",
    "away_form_goals_against",
    "home_form_goal_diff",
    "away_form_goal_diff",
    "home_form_wins",
    "away_form_wins",
    # Форма на своём/чужом поле
    "home_venue_form_points",
    "away_venue_form_points",
    "home_venue_form_gd",
    "away_venue_form_gd",
    # Глобальный Elo (между чемпионатами)
    "home_elo",
    "away_elo",
    "elo_diff",
    "home_elo_win_prob",
    "home_elo_adj",
    "away_elo_adj",
    "elo_adj_diff",
    # Сила чемпионата (1.0 = средний уровень)
    "home_champ_strength",
    "away_champ_strength",
    "champ_strength_diff",
    # Форма с учётом силы соперника
    "home_form_opp_adj_points",
    "away_form_opp_adj_points",
    "home_form_elo_perf",
    "away_form_elo_perf",
    "home_form_opp_adj_gd",
    "away_form_opp_adj_gd",
    # Отдых и H2H
    "home_rest_days",
    "away_rest_days",
    "rest_days_diff",
    "home_short_rest",
    "away_short_rest",
    "h2h_matches",
    "h2h_home_points",
    "h2h_avg_total_goals",
    "h2h_home_win_rate",
    # Серии и диффы (сводные признаки силы)
    "home_unbeaten_streak",
    "away_unbeaten_streak",
    "season_ppg_diff",
    "season_gd_diff",
    "form_points_diff",
    "form_gd_diff",
    "attack_strength_diff",
    "defense_strength_diff",
    "venue_ppg_diff",
    "venue_form_points_diff",
    # Poisson-ожидание голов (атака × оборона)
    "exp_home_goals",
    "exp_away_goals",
    "exp_total_goals",
    "exp_home_venue_goals",
    "exp_away_venue_goals",
]
